export const websiteData = {
  categories: {
    "buttons": [
      {
        name: "Flowchef",
        url: "https://www.flowchef.co/",
        image: "/images/buttons-1.webp",
        code: "https://codepen.io/ThunderFound/pen/QWJBQwo",
      },
      {
        name: "Rednecks",
        url: "https://redneck.media/",
        image: "/images/buttons-2.webp",
        gif: "/images/buttons-2g.webp ",
      },
      {
        name: "Spark",
        url: "https://codepen.io/lucasdellabella/pen/RwMyzRd",
        image: "/images/buttons-3.webp",
      },
      {
        name: "Vercel",
        url: "https://vercel.com/",
        image: "/images/buttons-4.webp",
      },
      {
        name: "CodePen",
        url: "https://codepen.io/",
        code: "https://codepen.io/Mimsoo/pen/oNvaVXx",
        image: "/images/buttons-5.webp",
      },
      {
        name: "Gumroad",
        url: "https://gumroad.com/",
        image: "/images/buttons-6.webp",
      },
      {
        name: "A_NG_D",
        url: "https://an.gd/",
        image: "/images/buttons-7.webp",
      },
      {
        name: "Sonderegger",
        url: "https://www.sonderegger.ch/en",
        image: "/images/buttons-8.webp",
        code: "https://codepen.io/kalisnetwork/pen/dyQqPzY",
      },
      {
        name: "AM-ARC",
        url: "https://am-arc.com/",
        image: "/images/buttons-9.webp",
      },
      {
        name: "Pierre Louis Design",
        url: "https://pierrelouis.design/",
        image: "/images/buttons-10.webp",
      },
      {
        name: "Blackbox",
        url: "https://www.useblackbox.io/",
        image: "/images/buttons-11.webp",
      },
      {
        name: "DoublePoint",
        url: "https://www.doublepoint.com/",
        image: "/images/buttons-12.webp",
      },
      {
        name: "Threads.com",
        url: "https://threads.com/",
        image: "/images/buttons-13.webp",
      },
      {
        name: "Starlight",
        url: "https://www.starlight.money/",
        image: "/images/buttons-14.webp",
      },
      {
        name: "Clay",
        url: "https://clay.earth/",
        image: "/images/buttons-15.webp",
      },
      {
        name: "Quai Network",
        url: "https://qu.ai/#articles",
        image: "/images/buttons-16.webp",
        gif: "/images/buttons-16g.webp ",
      },
      {
        name: "Cosmos",
        url: "https://www.cosmos.so/",
        image: "/images/buttons-17.webp",
        gif: "/images/buttons-17g.webp ",
      },
      {
        name: "CodeDotSpirit",
        url: "https://codedotspirit.dev/",
        image: "/images/buttons-18.webp",
        gif: "/images/buttons-18g.webp ",
      },
      {
        name: "Poppr 1",
        url: "https://www.poppr.be/",
        image: "/images/buttons-19.webp",
        gif: "/images/buttons-19g.webp ",
      },
      {
        name: "Poppr 2",
        url: "https://www.poppr.be/",
        image: "/images/buttons-20.webp",
        gif: "/images/buttons-20g.webp ",
      },
      {
        name: "Chronicle HQ",
        url: "https://chroniclehq.com/",
        image: "/images/buttons-21.webp",
        gif: "/images/buttons-21g.webp ",
      },
      {
        name: "Nuxt",
        url: "https://nuxt.com/",
        image: "/images/buttons-22.webp",
      },
      {
        name: "App Embed",
        url: "https://appembed.netlify.app/#generate",
        image: "/images/buttons-23.webp",
        gif: "/images/buttons-23g.webp",
      },
      {
        name: "Kaploom",
        url: "https://www.kaploom.com/",
        image: "/images/buttons-24.webp",
        gif: "/images/buttons-24g.webp",
      },
      {
        name: "Bolt",
        url: "https://www.bolt.com/",
        image: "/images/buttons-25.webp",
        gif: "/images/buttons-25g.webp",
      },
      {
        name: "Studio Kingdom",
        url: "https://studiokingdom.co.kr/en/",
        image: "/images/buttons-26.webp",
        gif: "/images/buttons-26g.webp",
      },
    ],
    "links": [
      {
        name: "Oaks Lane",
        url: "https://oakslane.ch/en",
        image: "/images/links-1.webp",
        gif: "/images/links-1g.webp",
      },
      {
        name: "Hackernoon",
        url: "https://hackernoon.com/",
        image: "/images/links-2.webp",
        gif: "/images/links-2g.webp",
      },
      {
        name: "Realtime Colors",
        url: "https://realtimecolors.com/",
        code: "https://codepen.io/Juxtopposed/pen/poQVrPX",
        image: "/images/links-3.webp",
        gif: "/images/links-3g.webp",
      },
      {
        name: "UBAC Store",
        url: "https://ubac-store.com/en/",
        image: "/images/links-4.webp",
        gif: "/images/links-4g.webp",
        code: "https://codepen.io/kalisnetwork/pen/yLQxNQY",
      },
      {
        name: "Awwwards",
        url: "https://www.awwwards.com/",
        image: "/images/links-5.webp",
        gif: "/images/links-5g.webp",
      },
      {
        name: "JTB Studios",
        url: "https://www.jtbstudios.com.au/",
        image: "/images/links-6.webp",
        gif: "/images/links-6g.webp",
      },
      {
        name: "Mack & Pouya",
        url: "https://mackpouya.webflow.io//",
        image: "/images/links-7.webp",
        gif: "/images/links-7g.webp",
      },
      {
        name: "Poppr",
        url: "https://www.poppr.be/",
        image: "/images/links-8.webp",
        gif: "/images/links-8g.webp",
      },
    ],
    "grids": [
      {
        name: "'22 Companies.Tools",
        url: "https://recap.companies.tools/",
        image: "/images/grids-1.webp",
      },
      {
        name: "Realtime Colors",
        url: "https://realtimecolors.com/?colors=faf8fc-160d1c-dfcfb9-261631-5eb591",
        image: "/images/grids-2.webp",
      },
      {
        name: "Apple iPhone 14",
        url: "https://www.apple.com/iphone-14/",
        image: "/images/grids-3.webp",
      },
      {
        name: "Reflect",
        url: "https://reflect.app/home",
        image: "/images/grids-4.webp",
      },
      {
        name: "Tabulio",
        url: "https://tabulio.com/",
        image: "/images/grids-5.webp",
      },
      {
        name: "LinkTree",
        url: "https://linktr.ee/",
        image: "/images/grids-6.webp",
      },
      {
        name: "Starlight",
        url: "https://www.starlight.money/",
        image: "/images/grids-7.webp",
      },
      {
        name: "Clay",
        url: "https://clay.earth/",
        image: "/images/grids-8.webp",
      },
      {
        name: "Vape",
        url: "https://www.vape.gg/",
        image: "/images/grids-9.webp",
      },
      {
        name: "CodeDotSpirit",
        url: "https://codedotspirit.dev/",
        image: "/images/grids-10.webp",
        gif: "/images/grids-10g.webp ",
      },
      {
        name: "Johannes Iilahti",
        url: "https://johannesiilahti.com/",
        image: "/images/grids-11.webp",
      },
      {
        name: "Raycast",
        url: "https://www.raycast.com/",
        image: "/images/grids-12.webp",
      },
      {
        name: "Diagram",
        url: "https://diagram.com/",
        image: "/images/grids-13.webp",
      },
      {
        name: "Bolt",
        url: "https://www.bolt.com/",
        image: "/images/grids-14.webp",
      },
      {
        name: "Railway",
        url: "https://railway.app/careers",
        image: "/images/grids-15.webp",
      },
    ],
    "custom-cursor": [
      {
        name: "Rednecks",
        url: "https://redneck.media/",
        image: "/images/cursor-1.webp",
        gif: "/images/cursor-1g.webp ",
      },
      {
        name: "AM-ARC 1",
        url: "https://am-arc.com/",
        image: "/images/cursor-2.webp",
        gif: "/images/cursor-2g.webp ",
      },
      {
        name: "AM-ARC 2",
        url: "https://am-arc.com/",
        image: "/images/cursor-3.webp",
        gif: "/images/cursor-3g.webp ",
      },
      {
        name: "Empathy Experiment",
        url: "https://www.empathyexperiment.com/",
        image: "/images/cursor-4.webp",
        gif: "/images/cursor-4g.webp ",
      },
      {
        name: "DoublePoint",
        url: "https://www.doublepoint.com/",
        image: "/images/cursor-5.webp",
        gif: "/images/cursor-5g.webp ",
      },
      {
        name: "Google Design",
        url: "https://design.google/",
        image: "/images/cursor-6.webp",
        gif: "/images/cursor-6g.webp ",
      },
      {
        name: "Kubota Future Cube",
        url: "https://www.kubota.com/futurecube/",
        image: "/images/cursor-7.webp",
        gif: "/images/cursor-7g.webp ",
      },
      {
        name: "JTB Studios",
        url: "https://www.jtbstudios.com.au/",
        image: "/images/cursor-8.webp",
        gif: "/images/cursor-8g.webp ",
      },
      {
        name: "Yuu Dev",
        url: "https://yuukun.dev/",
        image: "/images/cursor-9.webp",
        gif: "/images/cursor-9g.webp ",
      },
      {
        name: "Kaploom",
        url: "https://www.kaploom.com/",
        image: "/images/cursor-10.webp",
        gif: "/images/cursor-10g.webp ",
      },
      {
        name: "All Gold",
        url: "https://allgold.com/",
        image: "/images/cursor-11.webp",
        gif: "/images/cursor-11g.webp ",
      },
      {
        name: "Looksie",
        url: "https://looskie.com/",
        image: "/images/cursor-12.webp",
      },
      {
        name: "Teamgeek",
        url: "https://www.teamgeek.io/",
        image: "/images/cursor-13.webp",
        gif: "/images/cursor-13g.webp ",
      },
    ],
    "progress-bar": [
      {
        name: "Kubota Future Cube",
        url: "https://www.kubota.com/futurecube/",
        image: "/images/progress-bar-1.webp",
        gif: "/images/progress-bar-1g.webp ",
      },
      {
        name: "The Boat",
        url: "https://www.sbs.com.au/theboat/",
        image: "/images/progress-bar-2.webp",
        gif: "/images/progress-bar-2g.webp ",
      },
      {
        name: "Thomas Bosc",
        url: "https://thomasbosc.com/",
        image: "/images/progress-bar-3.webp",
        gif: "/images/progress-bar-3g.webp ",
      },
    ],
    "loading-animation": [
      {
        name: "Quai Network",
        url: "https://qu.ai/#articles",
        image: "/images/loading-1.webp",
        gif: "/images/loading-1g.webp ",
      },
      {
        name: "Minh Pham",
        url: "https://minhpham.design/",
        image: "/images/loading-2.webp",
        gif: "/images/loading-2g.webp ",
      },
      {
        name: "Edwardh",
        url: "https://www.edwardh.io/",
        image: "/images/loading-3.webp",
        gif: "/images/loading-3g.webp ",
      },
    ],
    "cards": [
      {
        name: "Quai Network",
        url: "https://qu.ai/#what-can-you-build",
        image: "/images/cards-1.webp",
      },
      {
        name: "Croma",
        url: "https://wearecroma.it/",
        image: "/images/cards-2.webp",
      },
      {
        name: "Nuxt",
        url: "https://nuxt.com/",
        image: "/images/cards-3.webp",
        gif: "/images/cards-3g.webp ",
      },
      {
        name: "Riot Games",
        url: "https://www.riotgames.com/en",
        image: "/images/cards-4.webp",
        gif: "/images/cards-4g.webp ",
      },
    ],
    "text-effects": [
      {
        name: "Quai Network",
        url: "https://www.kubota.com/futurecube/",
        image: "/images/text-effects-1.webp",
        gif: "/images/text-effects-1g.webp ",
      },
      {
        name: "Minh Pham",
        url: "https://minhpham.design/",
        image: "/images/text-effects-2.webp",
        gif: "/images/text-effects-2g.webp ",
      },
      {
        name: "Chronicle HQ",
        url: "https://chroniclehq.com/",
        image: "/images/text-effects-3.webp",
        gif: "/images/text-effects-3g.webp ",
      },
      {
        name: "Kaploom",
        url: "https://www.kaploom.com/",
        image: "/images/text-effects-4.webp",
        gif: "/images/text-effects-4g.webp ",
      },
    ],
    "hover-effects": [
      {
        name: "Quai Network",
        url: "https://qu.ai/#articles",
        image: "/images/hover-effects-1.webp",
        gif: "/images/hover-effects-1g.webp ",
      },
    ],
    "hamburger-menu": [
      {
        name: "Croma",
        url: "https://wearecroma.it/",
        image: "/images/hamburger-menu-1.webp",
        gif: "/images/hamburger-menu-1g.webp ",
      },
      {
        name: "Poppr",
        url: "https://www.poppr.be/",
        image: "/images/hamburger-menu-2.webp",
        gif: "/images/hamburger-menu-2g.webp ",
      },
    ],
    "image-effects": [
      {
        name: "Outdated",
        url: "https://www.outdated.site/",
        image: "/images/image-effects-1.webp",
        gif: "/images/image-effects-1g.webp ",
      },
      {
        name: "Teamgeek",
        url: "https://www.teamgeek.io/",
        image: "/images/image-effects-2.webp",
        gif: "/images/image-effects-2g.webp ",
      },
    ],
    "border-effects": [
      {
        name: "Raycast",
        url: "https://www.raycast.com/",
        image: "/images/border-effects-1.webp",
      },
      {
        name: "Poppr",
        url: "https://www.poppr.be/",
        image: "/images/border-effects-2.webp",
        gif: "/images/border-effects-2g.webp ",
      },
      {
        name: "Nuxt",
        url: "https://nuxt.com/",
        image: "/images/border-effects-3.webp",
        gif: "/images/border-effects-3g.webp ",
      },
      {
        name: "Riot Games",
        url: "https://www.riotgames.com/en",
        image: "/images/border-effects-4.webp",
        gif: "/images/border-effects-4g.webp ",
      },
    ],
    "interactive-elements": [
      {
        name: "Superlist",
        url: "https://www.superlist.com/ ",
        image: "/images/interactive-1.webp",
        gif: "/images/interactive-1g.webp ",
      },
      {
        name: "Thomas Bosc",
        url: "https://thomasbosc.com/",
        image: "/images/interactive-2.webp",
        gif: "/images/interactive-2g.webp ",
      },
    ],
    "3D": [
      {
        name: "Kubota Future Cube",
        url: "https://www.kubota.com/futurecube/",
        image: "/images/3d-1.webp",
        gif: "/images/3d-1g.webp",
      },
      {
        name: "Thomas Bosc",
        url: "https://thomasbosc.com/",
        image: "/images/3d-2.webp",
        gif: "/images/3d-2g.webp ",
      },
      {
        name: "Active Theory",
        url: "https://activetheory.com/",
        image: "/images/3d-3.webp",
        gif: "/images/3d-3g.webp ",
      },
      {
        name: "Joshua's World",
        url: "https://www.joshuas.world/",
        image: "/images/3d-4.webp",
        gif: "/images/3d-4g.webp",
      },
    ],
  },
};
